version: '3.8'

services:
  pokemon_api:
    build: .
    ports:
      - "3000:3000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/v1/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
